version: 2

project_name: webhook-to-redis

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    - git push
    - git push --tags
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/sikalabs/webhook-to-redis/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: "6"
    binary: webhook-to-redis

archives:
  - formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: webhook-to-redis
    repository:
      owner: sikalabs
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/sikalabs/webhook-to-redis
    url_template: "https://github.com/sikalabs/webhook-to-redis/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    caveats: "How to use this binary: https://github.com/sikalabs/webhook-to-redis"
    description: "webhook-to-redis"
    install: |
      bin.install "webhook-to-redis"
    test: |
      system "#{bin}/webhook-to-redis version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "sikalabs/webhook-to-redis:{{ .Tag }}"
      dockerfile: Dockerfile.goreleaser
      ids:
        - webhook-to-redis
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/webhook-to-redis"
        - "--label=maintainer=SikaLabs Opensource &lt;opensource@sikalabs.com&gt;"
    - goos: linux
      goarch: arm64
      image_templates:
        - "sikalabs/webhook-to-redis:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.goreleaser.arm64v8
      ids:
        - webhook-to-redis
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabs/webhook-to-redis"
        - "--label=maintainer=SikaLabs Opensource &lt;opensource@sikalabs.com&gt;"
