FROM debian:13-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY webhook-dispatcher /usr/local/bin/
ENV CONFIG=/config.yaml
CMD ["/usr/local/bin/webhook-dispatcher", "server"]
EXPOSE 8000
